spring.application.name=apigateway-service

spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT}

internal.api-key=${INTERNAL_API_KEY}

security.jwt.token.secret-key=${JWT_SECRET}

spring.cloud.gateway.routes[0].id=saga-auth-local
spring.cloud.gateway.routes[0].uri=forward:/api/auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/login, /api/auth/register
spring.cloud.gateway.routes[0].order=1

spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=${services.auth.url}
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/api/auth/**
spring.cloud.gateway.routes[1].order=2

spring.cloud.gateway.server.webflux.routes[2].id=user-service
spring.cloud.gateway.server.webflux.routes[2].uri=${services.user.url}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/users, /api/users/**, /api/cards, /api/cards/**

spring.cloud.gateway.server.webflux.routes[3].id=order-service
spring.cloud.gateway.server.webflux.routes[3].uri=${services.order.url}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/orders, /api/orders/**, /api/items, /api/items/**

spring.cloud.gateway.server.webflux.routes[4].id=payment-service
spring.cloud.gateway.server.webflux.routes[4].uri=${services.payment.url}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/payments, /api/payments/**

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

spring.web.error.include-binding-errors=always

spring.profiles.active=local



